/* The following code was generated by JFlex 1.4.3 on 15.16.10 21:11 */

package lv.modo.livescriptbrains.psi;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.TokenType;
import com.intellij.util.containers.Stack;

import lv.modo.livescriptbrains.psi.LiveScriptTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15.16.10 21:11 from the specification file
 * <tt>D:/home/martin/dev/misc/LiveScriptBrains/src/lv/modo/livescriptbrains/psi/LiveScript.flex</tt>
 */
public class OldLiveScriptLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int ISTRING = 10;
  public static final int SPLIT_OP = 20;
  public static final int OBJECT = 26;
  public static final int DSTRING = 8;
  public static final int STRING_SUSPENDED = 14;
  public static final int REGEX = 18;
  public static final int LIST = 22;
  public static final int COMMENT_BLOCK = 6;
  public static final int YYINITIAL = 0;
  public static final int STRING_VAR = 24;
  public static final int TSTRING = 16;
  public static final int INDENTED = 2;
  public static final int BLOCK_STATEMENT = 4;
  public static final int VSTRING = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  2,  2,  3,  3,  4,  4,  5,  6,  2,  2,  2,  2, 
     4,  4,  2,  2,  7,  7,  8,  9, 10, 10, 11, 12
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\40\1\1\1\0\1\3\1\2\22\0\1\40\1\63\1\42"+
    "\1\43\1\4\1\0\1\52\1\41\1\57\1\60\1\46\1\47\1\55"+
    "\1\5\1\15\1\45\1\11\2\7\1\10\6\6\1\54\1\37\1\53"+
    "\1\50\1\53\1\64\1\35\4\13\1\13\15\13\1\13\1\13\6\13"+
    "\1\61\1\36\1\62\1\53\1\14\1\0\1\31\1\67\1\65\1\24"+
    "\1\27\1\30\1\13\1\34\1\23\2\13\1\20\1\13\1\16\1\22"+
    "\2\13\1\26\1\32\1\25\1\17\1\21\1\66\1\13\1\33\1\13"+
    "\1\44\1\51\1\56\1\12\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\15\0\1\1\2\2\1\3\1\4\1\5\3\6\1\7"+
    "\1\10\12\4\1\11\1\1\1\12\1\1\1\13\1\14"+
    "\1\15\1\5\1\16\1\17\2\1\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\3\4\3\3\2\27\2\30"+
    "\1\31\1\30\1\32\1\33\1\3\1\34\1\3\1\34"+
    "\1\35\1\3\1\36\1\37\1\40\1\6\1\0\2\6"+
    "\1\0\1\4\1\41\4\4\2\11\7\4\2\30\3\0"+
    "\1\30\2\13\1\30\1\0\1\42\2\4\1\43\1\0"+
    "\1\44\1\45\1\46\12\4\1\30\1\0\1\30\1\47"+
    "\1\0\2\4\1\31\1\50\3\4\1\0\1\27\2\4"+
    "\1\0\1\51\1\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u02d8\0\u0310"+
    "\0\u0348\0\u0380\0\u02d8\0\u03b8\0\u03f0\0\u0428\0\u02d8\0\u0460"+
    "\0\u0498\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620"+
    "\0\u0658\0\u0690\0\u02d8\0\u06c8\0\u02d8\0\u0700\0\u0738\0\u0770"+
    "\0\u02d8\0\u07a8\0\u02d8\0\u02d8\0\u07e0\0\u0818\0\u02d8\0\u02d8"+
    "\0\u02d8\0\u02d8\0\u02d8\0\u02d8\0\u02d8\0\u0850\0\u0888\0\u08c0"+
    "\0\u02d8\0\u08f8\0\u0930\0\u02d8\0\u0968\0\u02d8\0\u09a0\0\u09d8"+
    "\0\u0a10\0\u02d8\0\u02d8\0\u0a48\0\u0a80\0\u0ab8\0\u02d8\0\u02d8"+
    "\0\u0af0\0\u02d8\0\u0b28\0\u02d8\0\u0b60\0\u0b98\0\u0b98\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u0380\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58"+
    "\0\u0380\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0"+
    "\0\u0f18\0\u06c8\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u02d8\0\u1110\0\u1148\0\u02d8\0\u1180\0\u11b8"+
    "\0\u02d8\0\u02d8\0\u11f0\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308"+
    "\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u0f88\0\u1420\0\u1030\0\u02d8"+
    "\0\u1458\0\u1490\0\u14c8\0\u02d8\0\u0380\0\u1500\0\u1538\0\u1570"+
    "\0\u15a8\0\u10d8\0\u15e0\0\u1618\0\u1650\0\u0380\0\u1688";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\24\1\27\2\22\1\30\1\31\1\32\1\22"+
    "\1\33\1\34\1\35\1\36\1\37\1\22\1\40\1\41"+
    "\2\22\1\42\1\22\1\43\1\44\1\45\1\21\1\46"+
    "\1\47\1\50\1\51\1\52\1\23\1\53\1\54\1\55"+
    "\1\56\1\27\1\57\1\60\1\16\1\61\1\62\1\63"+
    "\1\16\1\64\1\65\1\66\1\67\1\70\1\16\1\71"+
    "\1\72\1\73\1\22\1\23\1\24\1\25\1\26\1\24"+
    "\1\27\2\22\1\30\1\31\1\32\1\22\1\33\1\34"+
    "\1\35\1\36\1\37\1\22\1\40\1\41\2\22\1\42"+
    "\1\22\1\43\1\44\1\45\1\73\1\46\1\47\1\50"+
    "\1\51\1\52\1\23\1\53\1\54\1\55\1\56\1\27"+
    "\1\57\1\60\1\16\1\61\1\62\1\63\1\16\1\64"+
    "\1\65\1\66\1\67\1\70\1\16\1\0\66\16\2\74"+
    "\1\75\65\74\2\76\1\77\37\76\1\100\1\101\24\76"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\24\1\27\2\22\1\30\1\31\1\32\1\22"+
    "\1\33\1\34\1\35\1\36\1\37\1\22\1\40\1\41"+
    "\2\22\1\42\1\22\1\43\1\44\1\45\1\21\1\46"+
    "\1\47\1\50\1\51\1\52\1\23\1\53\1\54\1\55"+
    "\1\56\1\27\1\57\1\60\1\102\1\61\1\62\1\63"+
    "\1\16\1\64\1\65\1\66\1\67\1\70\1\16\1\71"+
    "\1\72\1\73\1\22\1\23\1\24\1\25\1\26\1\24"+
    "\1\27\2\22\1\30\1\31\1\32\1\22\1\33\1\34"+
    "\1\35\1\36\1\37\1\22\1\40\1\41\2\22\1\42"+
    "\1\22\1\43\1\44\1\45\1\73\1\46\1\47\1\50"+
    "\1\51\1\52\1\23\1\53\1\54\1\55\1\56\1\27"+
    "\1\57\1\60\1\102\1\61\1\62\1\63\1\16\1\64"+
    "\1\65\1\66\1\67\1\70\1\103\1\21\1\104\65\103"+
    "\1\16\2\105\1\106\1\22\1\23\1\24\1\25\1\26"+
    "\1\24\1\27\2\22\1\30\1\31\1\32\1\22\1\33"+
    "\1\34\1\35\1\36\1\37\1\22\1\40\1\41\2\22"+
    "\1\42\1\22\1\43\1\44\1\45\1\106\1\46\1\47"+
    "\1\50\1\51\1\52\1\23\1\53\1\54\1\55\1\56"+
    "\1\27\1\57\1\107\1\16\1\61\1\62\1\63\1\110"+
    "\1\64\1\65\1\66\1\67\1\70\1\16\2\105\1\111"+
    "\1\22\1\23\1\24\1\25\1\26\1\24\1\27\2\22"+
    "\1\30\1\31\1\32\1\22\1\33\1\34\1\35\1\36"+
    "\1\37\1\22\1\40\1\41\2\22\1\42\1\22\1\43"+
    "\1\44\1\45\1\111\1\46\1\47\1\50\1\51\1\52"+
    "\1\23\1\53\1\54\1\55\1\56\1\27\1\57\1\107"+
    "\1\16\1\61\1\62\1\63\1\110\1\64\1\65\1\66"+
    "\1\67\1\70\1\112\1\0\2\112\1\113\6\112\2\113"+
    "\1\112\17\113\30\112\3\113\1\16\2\105\1\106\1\22"+
    "\1\23\1\24\1\25\1\26\1\24\1\27\2\22\1\30"+
    "\1\31\1\32\1\22\1\33\1\34\1\35\1\36\1\37"+
    "\1\22\1\40\1\41\2\22\1\42\1\22\1\43\1\44"+
    "\1\45\1\106\1\46\1\47\1\50\1\51\1\52\1\23"+
    "\1\53\1\54\1\55\1\56\1\27\1\57\1\107\1\114"+
    "\1\61\1\62\1\63\1\16\1\64\1\65\1\66\1\67"+
    "\1\70\1\16\2\105\1\111\1\22\1\23\1\24\1\25"+
    "\1\26\1\24\1\27\2\22\1\30\1\31\1\32\1\22"+
    "\1\33\1\34\1\35\1\36\1\37\1\22\1\40\1\41"+
    "\2\22\1\42\1\22\1\43\1\44\1\45\1\111\1\46"+
    "\1\47\1\50\1\51\1\52\1\23\1\53\1\54\1\55"+
    "\1\56\1\27\1\57\1\107\1\114\1\61\1\62\1\63"+
    "\1\16\1\64\1\65\1\66\1\67\1\70\71\0\1\17"+
    "\71\0\1\21\34\0\1\21\33\0\6\22\1\0\2\22"+
    "\1\0\17\22\30\0\3\22\6\0\4\115\1\116\1\117"+
    "\1\115\1\120\17\117\30\0\3\117\6\0\4\24\1\116"+
    "\1\117\1\115\1\120\17\117\30\0\3\117\6\0\1\115"+
    "\1\24\1\115\1\24\1\116\1\117\1\115\1\120\17\117"+
    "\30\0\3\117\15\0\1\121\56\0\6\22\1\0\2\22"+
    "\1\0\1\22\1\122\2\22\1\123\4\22\1\124\5\22"+
    "\30\0\3\22\4\0\6\22\1\0\2\22\1\0\1\125"+
    "\16\22\30\0\3\22\4\0\6\22\1\0\2\22\1\0"+
    "\4\22\1\126\12\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\1\123\6\22\1\127\2\22\1\130\4\22"+
    "\30\0\3\22\4\0\6\22\1\0\2\22\1\0\1\131"+
    "\11\22\1\131\4\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\4\22\1\131\4\22\1\132\5\22\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\10\22\1\133"+
    "\5\22\1\134\30\0\3\22\4\0\6\22\1\0\2\22"+
    "\1\0\2\22\1\135\14\22\30\0\3\22\4\0\6\22"+
    "\1\0\2\22\1\0\4\22\1\136\6\22\1\137\3\22"+
    "\30\0\3\22\4\0\6\22\1\0\2\22\1\0\11\22"+
    "\1\140\5\22\30\0\3\22\1\141\1\21\1\104\1\142"+
    "\33\141\1\0\1\143\14\141\2\0\1\141\1\0\1\141"+
    "\1\0\5\141\36\144\1\145\2\144\1\146\26\144\36\147"+
    "\1\150\3\147\1\151\1\0\24\147\1\50\1\0\66\50"+
    "\46\0\1\152\72\0\1\153\70\0\1\153\21\0\6\22"+
    "\1\0\2\22\1\0\2\22\1\154\14\22\30\0\3\22"+
    "\4\0\6\22\1\0\2\22\1\0\16\22\1\155\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\15\22\1\131"+
    "\1\22\30\0\3\22\1\0\1\71\66\0\1\156\1\71"+
    "\1\72\1\73\34\156\1\73\27\156\1\0\1\74\67\0"+
    "\1\76\130\0\1\157\31\0\1\160\6\0\2\160\1\0"+
    "\17\160\7\0\1\161\20\0\3\160\1\0\1\21\1\0"+
    "\1\21\34\0\1\21\30\0\3\105\34\0\1\105\30\0"+
    "\2\105\1\106\34\0\1\106\27\0\1\156\2\105\1\111"+
    "\34\156\1\111\27\156\4\0\6\113\1\0\2\113\1\0"+
    "\17\113\30\0\3\113\6\0\4\115\1\0\1\117\1\115"+
    "\1\120\17\117\30\0\3\117\6\0\4\117\1\0\1\117"+
    "\2\0\17\117\30\0\3\117\6\0\4\120\1\0\1\117"+
    "\1\120\1\0\17\117\30\0\3\117\15\0\1\162\56\0"+
    "\6\22\1\0\2\22\1\0\2\22\1\163\14\22\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\17\22\30\0"+
    "\1\22\1\131\1\22\4\0\6\22\1\0\2\22\1\0"+
    "\2\22\1\164\14\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\5\22\1\165\11\22\30\0\3\22\4\0"+
    "\6\22\1\0\2\22\1\0\16\22\1\166\30\0\3\22"+
    "\4\0\6\22\1\0\2\22\1\0\12\22\1\123\4\22"+
    "\30\0\3\22\4\0\6\22\1\0\2\22\1\0\2\22"+
    "\1\167\14\22\30\0\3\22\4\0\6\22\1\0\2\22"+
    "\1\0\1\22\1\170\15\22\30\0\3\22\4\0\6\22"+
    "\1\0\2\22\1\0\5\22\1\171\3\22\1\172\5\22"+
    "\30\0\3\22\4\0\6\22\1\0\2\22\1\0\14\22"+
    "\1\173\2\22\30\0\3\22\4\0\6\22\1\0\2\22"+
    "\1\0\10\22\1\131\6\22\30\0\3\22\4\0\6\22"+
    "\1\0\2\22\1\0\2\22\1\174\14\22\30\0\3\22"+
    "\4\0\6\22\1\0\2\22\1\0\14\22\1\123\2\22"+
    "\30\0\3\22\1\141\2\0\34\141\2\0\14\141\2\0"+
    "\1\141\1\0\1\141\1\0\5\141\1\0\1\21\1\104"+
    "\1\143\34\0\1\143\27\0\36\144\1\145\2\144\1\76"+
    "\64\144\1\145\2\144\1\175\26\144\41\0\1\176\26\0"+
    "\36\147\1\150\3\147\1\76\1\0\62\147\1\150\3\147"+
    "\1\177\1\0\24\147\42\0\1\200\25\0\46\152\1\201"+
    "\21\152\4\0\6\22\1\0\2\22\1\0\13\22\1\202"+
    "\3\22\30\0\3\22\4\0\6\22\1\0\2\22\1\0"+
    "\5\22\1\203\11\22\30\0\3\22\42\0\1\204\31\0"+
    "\6\160\1\0\2\160\1\0\17\160\30\0\3\160\4\0"+
    "\6\22\1\0\2\22\1\0\2\22\1\205\14\22\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\11\22\1\206"+
    "\5\22\30\0\3\22\4\0\6\22\1\0\2\22\1\0"+
    "\6\22\1\205\10\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\11\22\1\207\5\22\30\0\3\22\4\0"+
    "\6\22\1\0\2\22\1\0\11\22\1\210\5\22\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\11\22\1\123"+
    "\5\22\30\0\3\22\4\0\6\22\1\0\2\22\1\0"+
    "\14\22\1\131\2\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\1\131\16\22\30\0\3\22\4\0\6\22"+
    "\1\0\2\22\1\0\11\22\1\131\5\22\30\0\3\22"+
    "\4\0\6\22\1\0\2\22\1\0\14\22\1\170\2\22"+
    "\30\0\3\22\41\176\1\211\26\176\45\152\1\212\1\201"+
    "\21\152\4\0\6\22\1\0\2\22\1\0\14\22\1\213"+
    "\2\22\30\0\3\22\4\0\6\22\1\0\2\22\1\0"+
    "\2\22\1\173\14\22\30\0\3\22\4\0\6\22\1\0"+
    "\2\22\1\0\14\22\1\171\2\22\30\0\3\22\4\0"+
    "\6\22\1\0\2\22\1\0\10\22\1\214\6\22\30\0"+
    "\3\22\4\0\6\22\1\0\2\22\1\0\7\22\1\173"+
    "\7\22\30\0\3\22\41\0\1\215\32\0\6\22\1\0"+
    "\2\22\1\0\14\22\1\216\2\22\30\0\3\22\4\0"+
    "\6\22\1\0\2\22\1\0\17\22\30\0\1\22\1\217"+
    "\1\22\41\0\1\76\32\0\6\22\1\0\2\22\1\0"+
    "\5\22\1\135\11\22\30\0\3\22";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5824];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\15\0\2\11\3\1\1\11\3\1\1\11\13\1\1\11"+
    "\1\1\1\11\3\1\1\11\1\1\2\11\2\1\7\11"+
    "\3\1\1\11\2\1\1\11\1\1\1\11\3\1\2\11"+
    "\3\1\2\11\1\1\1\11\1\1\1\11\1\1\1\0"+
    "\2\1\1\0\21\1\3\0\4\1\1\0\1\11\2\1"+
    "\1\11\1\0\1\1\2\11\13\1\1\0\1\1\1\11"+
    "\1\0\2\1\1\11\4\1\1\0\3\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /**
     * Stack for keeping track of lexical states.
     */
    private Stack<Integer> _states = new Stack<Integer>();

    /**
     * Are indents tabs instead of spaces?
     */
    private static Boolean _tabIndents = null;

    /**
     * Current indent baseline.
     */
    private static int _currentIndent = 0;

    private static Boolean _debug = true;


    private void _switchToState(int state) {
        if (_debug)
            System.out.println("Switching to state " + _stateName(state) + ".");
        yybegin(state);
    }

    /**
     * Enter a lexical state and push the previous one to the stack.
     */
    private void _enterState(int state) {
        if (_debug)
            System.out.println("Entering state " + _stateName(state) + ".");
        _states.push(yystate());
        yybegin(state);
    }

    /**
     * Leave a lexical state and return to the previous one (if any).
     * @returns boolean True if state was switched to a previous one, false if already at YYINITIAL.
     */
    private boolean _exitState() {
        if (_states.empty()) {
            if (_debug)
                System.out.println("State stack empty, defaulting to YYINITIAL.");
            yybegin(YYINITIAL);
            return false;
        }
        else {
            int newState = _states.pop();
            if (_debug)
                System.out.println("Exiting state " + _stateName(yystate()) + ", state is now " + _stateName(newState));
            yybegin(newState);
            return true;
        }
    }

    /**
     * Move the input position back to the start of the matched string.
     */
    private void _rewind() {
        yypushback(yylength());
    }

    /**
     * Move input position backwards.
     */
    private void _rewindBy(int count) {
        yypushback(count);
    }

    private void _advanceBy(int count) {
        _rewindBy(-count);
    }

    /**
     * Move the input position back to the first position of a given string
     */
    private boolean _rewindTo(String text) {
        final int position = yytext().toString().indexOf(text);

        if (position != -1) {
          _rewindBy(position);
          return true;
        }

        return false;
    }

    private IElementType _out(IElementType input) {
        if (_debug)
            System.out.println("Matched [" + yytext() + "] as " + input);
        return input;
    }
    private String[] _stateNames = new String[] {
        "YYINITIAL",
        "INDENTED",
        "BLOCK_STATEMENT",
        "COMMENT_BLOCK",
        "DSTRING",
        "ISTRING",
        "VSTRING",
        "STRING_SUSPENDED",
        "TSTRING",
        "REGEX",
        "SPLIT_OP",
        "LIST",
        "STRING_VAR",
        "OBJECT",
    };
    private String _stateName(int state) {
        return _stateNames[state / 2];
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OldLiveScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	if (_debug)
    	System.out.println("End of file reached, clearing out state stack.");
    _states.clear();
    return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL-1] : zzBufferL.charAt(zzMarkedPosL-1))) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return _out(LiveScriptTypes.ASSIGN);
          }
        case 42: break;
        case 22: 
          { return _out(LiveScriptTypes.Q);
          }
        case 43: break;
        case 31: 
          { _exitState(); return _out(LiveScriptTypes.IDENTIFIER);
          }
        case 44: break;
        case 28: 
          { return _out(LiveScriptTypes.SEPARATOR);
          }
        case 45: break;
        case 8: 
          { return _out(LiveScriptTypes.DOT);
          }
        case 46: break;
        case 20: 
          { _enterState(LIST); return _out(LiveScriptTypes.LIST_START);
          }
        case 47: break;
        case 35: 
          { _rewindBy(1); return _out(LiveScriptTypes.INDENT);
          }
        case 48: break;
        case 18: 
          { return _out(LiveScriptTypes.PAREN_L);
          }
        case 49: break;
        case 39: 
          { _enterState(TSTRING); return _out(LiveScriptTypes.STRING_START);
          }
        case 50: break;
        case 14: 
          { _enterState(SPLIT_OP); return _out(LiveScriptTypes.PLUS);
          }
        case 51: break;
        case 10: 
          { return _out(LiveScriptTypes.SEMICOLON);
          }
        case 52: break;
        case 17: 
          { return _out(LiveScriptTypes.COMMA);
          }
        case 53: break;
        case 34: 
          { return _out(LiveScriptTypes.LOGIC_OP);
          }
        case 54: break;
        case 26: 
          { _exitState(); return _out(LiveScriptTypes.ISTRING);
          }
        case 55: break;
        case 4: 
          { return _out(LiveScriptTypes.IDENTIFIER);
          }
        case 56: break;
        case 29: 
          { _exitState(); return _out(LiveScriptTypes.LIST_END);
          }
        case 57: break;
        case 11: 
          { _rewind(); _advanceBy(1); _enterState(DSTRING); return _out(LiveScriptTypes.STRING_START);
          }
        case 58: break;
        case 38: 
          { return _out(LiveScriptTypes.YADA);
          }
        case 59: break;
        case 41: 
          { return _out(LiveScriptTypes.CLASS);
          }
        case 60: break;
        case 2: 
          { return _out(LiveScriptTypes.NEWLINE);
          }
        case 61: break;
        case 19: 
          { return _out(LiveScriptTypes.PAREN_R);
          }
        case 62: break;
        case 40: 
          { return _out(LiveScriptTypes.EMPTY);
          }
        case 63: break;
        case 12: 
          { return _out(LiveScriptTypes.COMMENT_LINE);
          }
        case 64: break;
        case 6: 
          { return _out(LiveScriptTypes.NUMBER);
          }
        case 65: break;
        case 24: 
          { return _out(LiveScriptTypes.STRING);
          }
        case 66: break;
        case 27: 
          { _rewindBy(1); _exitState();
          }
        case 67: break;
        case 32: 
          { _exitState(); return _out(LiveScriptTypes.OBJ_END);
          }
        case 68: break;
        case 23: 
          { return _out(LiveScriptTypes.COMMENT_BLOCK);
          }
        case 69: break;
        case 3: 
          { return _out(TokenType.WHITE_SPACE);
          }
        case 70: break;
        case 7: 
          { return _out(LiveScriptTypes.MISC_OP);
          }
        case 71: break;
        case 25: 
          { _exitState(); return _out(LiveScriptTypes.STRING_END);
          }
        case 72: break;
        case 33: 
          { return _out(LiveScriptTypes.BOOLEAN);
          }
        case 73: break;
        case 36: 
          { _rewind(); _advanceBy(1); _enterState(STRING_VAR); return _out(LiveScriptTypes.ESCAPE_CHAR);
          }
        case 74: break;
        case 1: 
          { if (_debug) System.out.println("State is " + _stateName(yystate())); return _out(TokenType.BAD_CHARACTER);
          }
        case 75: break;
        case 16: 
          { return _out(LiveScriptTypes.COLON);
          }
        case 76: break;
        case 37: 
          { _enterState(ISTRING); return _out(LiveScriptTypes.ISTRING);
          }
        case 77: break;
        case 13: 
          { _enterState(OBJECT); return _out(LiveScriptTypes.OBJ_START);
          }
        case 78: break;
        case 30: 
          { _exitState(); _rewindBy(1);
          }
        case 79: break;
        case 21: 
          { return _out(LiveScriptTypes.BANG);
          }
        case 80: break;
        case 9: 
          { return _out(LiveScriptTypes.KEYWORD);
          }
        case 81: break;
        case 5: 
          { _enterState(SPLIT_OP); return _out(LiveScriptTypes.MATH_OP);
          }
        case 82: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
