/* The following code was generated by JFlex 1.4.3 on 15.1.3 16:14 */

package com.simpleplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.simpleplugin.psi.LiveScriptTypes;
import com.intellij.psi.TokenType;
import com.intellij.util.containers.Stack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15.1.3 16:14 from the specification file
 * <tt>C:/home/martin/dev/misc/LiveScriptBrains/src/com/simpleplugin/LiveScript.flex</tt>
 */
class LiveScriptLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING_SUSPENDED = 12;
  public static final int YYINITIAL = 0;
  public static final int BLOCK_STATEMENT = 4;
  public static final int SIMPLE_STRING_STARTED = 6;
  public static final int INDENTED = 2;
  public static final int STRING_VARIABLE = 10;
  public static final int FULL_STRING_STARTED = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  2,  1,  3,  4,  4,  5,  5,  6,  6,  7, 7
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\45\1\32\1\0\1\44\1\33\22\0\1\45\1\0\1\35"+
    "\1\41\1\37\1\34\1\0\1\31\1\0\1\30\1\43\1\36\1\30"+
    "\1\40\1\10\1\42\1\4\2\2\1\3\6\1\1\0\1\30\1\0"+
    "\1\36\3\0\32\6\1\0\1\27\1\30\1\0\1\7\1\0\1\24"+
    "\2\6\1\17\1\22\1\23\2\6\1\16\2\6\1\13\1\6\1\11"+
    "\1\15\2\6\1\21\1\25\1\20\1\12\1\14\2\6\1\26\1\6"+
    "\1\46\1\0\1\47\1\5\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\10\0\1\1\3\2\7\3\1\1\1\4\2\5\1\1"+
    "\1\6\1\7\1\10\1\7\1\11\1\12\1\13\1\14"+
    "\1\13\1\1\1\13\1\1\2\15\1\16\3\15\1\17"+
    "\1\20\1\21\1\2\1\0\2\2\1\3\1\22\5\3"+
    "\1\23\3\0\5\24\1\0\1\25\1\26\1\2\4\3"+
    "\3\0\1\10\1\0\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0140\0\u0348\0\u0370"+
    "\0\u0140\0\u0140\0\u0398\0\u03c0\0\u03e8\0\u0140\0\u0410\0\u0438"+
    "\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0140\0\u0550"+
    "\0\u0578\0\u05a0\0\u05c8\0\u0140\0\u0140\0\u05f0\0\u0618\0\u0640"+
    "\0\u0668\0\u0690\0\u01e0\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758"+
    "\0\u02f8\0\u0780\0\u07a8\0\u0488\0\u0410\0\u0438\0\u04b0\0\u0140"+
    "\0\u04d8\0\u04d8\0\u07d0\0\u0140\0\u0618\0\u07f8\0\u0820\0\u0848"+
    "\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u07a8\0\u0910\0\u0910";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\11\1\12\1\13\1\14\1\12\1\11\2\15\1\11"+
    "\1\16\2\15\1\17\1\20\2\15\1\21\2\15\1\22"+
    "\2\15\1\23\1\24\1\11\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\15\1\32\1\33\1\34\1\32\2\35"+
    "\1\11\1\36\32\11\1\0\14\11\1\36\32\37\1\0"+
    "\1\11\5\37\1\40\2\37\1\41\1\42\34\37\1\0"+
    "\1\11\5\37\1\40\2\37\1\43\1\44\2\37\27\45"+
    "\1\46\1\45\1\47\16\45\27\50\1\51\5\50\1\47"+
    "\3\50\1\52\6\50\6\11\2\53\1\11\16\53\3\11"+
    "\1\0\4\11\1\53\7\11\1\36\32\54\1\0\14\54"+
    "\1\55\51\0\4\56\1\57\1\60\1\56\1\61\16\60"+
    "\22\0\4\12\1\57\1\60\1\56\1\61\16\60\22\0"+
    "\1\56\1\12\1\56\1\12\1\57\1\60\1\56\1\61"+
    "\16\60\22\0\4\15\1\0\2\15\1\0\16\15\10\0"+
    "\2\15\10\0\4\15\1\0\2\15\1\0\1\15\1\62"+
    "\2\15\1\63\11\15\10\0\2\15\10\0\4\15\1\0"+
    "\2\15\1\0\4\15\1\64\11\15\10\0\2\15\10\0"+
    "\4\15\1\0\2\15\1\0\1\63\11\15\1\65\3\15"+
    "\10\0\2\15\10\0\4\15\1\0\2\15\1\0\10\15"+
    "\1\66\5\15\10\0\2\15\10\0\4\15\1\0\2\15"+
    "\1\0\13\15\1\67\2\15\10\0\2\15\10\0\4\15"+
    "\1\0\2\15\1\0\11\15\1\70\4\15\10\0\2\15"+
    "\7\0\30\71\1\0\1\71\2\0\11\71\1\0\1\71"+
    "\32\0\1\72\50\0\1\26\52\0\1\31\12\0\32\33"+
    "\1\0\15\33\43\0\1\73\50\0\2\35\2\0\32\37"+
    "\1\0\15\37\32\40\1\0\15\40\32\37\1\0\6\37"+
    "\1\40\2\37\2\41\2\37\41\0\1\40\2\0\2\74"+
    "\2\0\32\75\1\0\1\37\5\75\1\76\2\75\1\77"+
    "\1\43\2\75\32\100\2\0\5\100\1\76\2\100\1\101"+
    "\1\102\2\100\27\45\1\46\1\45\1\0\45\45\1\46"+
    "\20\45\27\50\1\51\5\50\1\0\3\50\1\0\35\50"+
    "\1\51\20\50\6\0\2\103\1\0\16\103\10\0\1\103"+
    "\6\0\1\104\2\0\4\53\1\0\2\53\1\0\16\53"+
    "\10\0\2\53\10\0\4\56\1\0\1\60\1\56\1\61"+
    "\16\60\22\0\4\105\1\0\1\105\2\0\16\105\27\0"+
    "\1\60\2\0\16\60\22\0\4\61\1\0\1\60\1\61"+
    "\1\0\16\60\22\0\4\15\1\0\2\15\1\0\2\15"+
    "\1\106\13\15\10\0\2\15\10\0\4\15\1\0\2\15"+
    "\1\0\5\15\1\107\10\15\10\0\2\15\10\0\4\15"+
    "\1\0\2\15\1\0\12\15\1\63\3\15\10\0\2\15"+
    "\10\0\4\15\1\0\2\15\1\0\1\15\1\110\14\15"+
    "\10\0\2\15\10\0\4\15\1\0\2\15\1\0\2\15"+
    "\1\111\13\15\10\0\2\15\10\0\4\15\1\0\2\15"+
    "\1\0\14\15\1\63\1\15\10\0\2\15\40\0\1\112"+
    "\16\0\43\73\1\113\4\73\1\0\4\103\1\0\2\103"+
    "\1\0\16\103\10\0\2\103\10\0\4\15\1\0\2\15"+
    "\1\0\2\15\1\63\13\15\10\0\2\15\10\0\4\15"+
    "\1\0\2\15\1\0\6\15\1\63\7\15\10\0\2\15"+
    "\10\0\4\15\1\0\2\15\1\0\11\15\1\63\4\15"+
    "\10\0\2\15\10\0\4\15\1\0\2\15\1\0\14\15"+
    "\1\110\1\15\10\0\2\15\7\0\31\112\1\114\16\112"+
    "\42\73\1\115\1\113\4\73\31\112\1\116\47\112\1\117"+
    "\16\112";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2360];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\10\0\1\11\14\1\1\11\2\1\2\11\3\1\1\11"+
    "\10\1\1\11\4\1\2\11\1\1\1\0\12\1\3\0"+
    "\3\1\1\11\1\1\1\0\1\1\1\11\5\1\3\0"+
    "\1\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /**
     * Stack for keeping track of lexical states.
     */
    private static Stack<Integer> _states = new Stack<Integer>();

    /**
     * Are indents tabs instead of spaces?
     */
    private static Boolean _tabIndents = null;

    /**
     * Indent stack to keep track of indentation levels.
     */
    private static Stack<Integer> _indents = new Stack<Integer>();

    /**
     * Current indent baseline.
     */
    private static int _currentIndent = 0;

    /**
     * Are we currently inside an indented block?
     */
    private static boolean _isIndented = false;

    /**
     * Start a new indented block (increase indent).
     */
    private IElementType _parseIndent(int count) {
        if (count > _currentIndent) {
            _indents.push(_currentIndent);
            _currentIndent += count;
            _enterState(INDENTED);
            return _out(LiveScriptTypes.INDENT);
        }
        else if (count < _currentIndent) {
            if (!_indents.empty())
                _currentIndent = _indents.pop();
            _exitState();
            if (_currentIndent < 1) {
                _isIndented = false;
            }
            return _out(LiveScriptTypes.DEDENT);
        }
        return null;
    }

    /**
     * Enter a lexical state and push the previous one to the stack.
     */
    private void _enterState(int state) {
        System.out.println("Entering state " + state);
        _states.push(yystate());
        yybegin(state);
    }

    /**
     * Leave a lexical state and return to the previous one (if any).
     * @returns boolean True if state was switched to a previous one, false if already at YYINITIAL.
     */
    private boolean _exitState() {
        if (_states.empty()) {
            System.out.println("State stack empty, defaulting to YYINITIAL.");
            yybegin(YYINITIAL);
            return false;
        }
        else {
            System.out.println("Exiting state...");
            yybegin(_states.pop());
            return true;
        }
    }

    /**
     * Move the input position back to the start of the matched string.
     */
    private void _rewind() {
        yypushback(yylength());
    }

    /**
     * Move input position backwards.
     */
    private void _rewindBy(int count) {
        yypushback(count);
    }

    /**
     * Move the input position back to the first position of a given string
     */
    private boolean _rewindTo(String text) {
        final int position = yytext().toString().indexOf(text);

        if (position != -1) {
          _rewindBy(position);
          return true;
        }

        return false;
    }

    private IElementType _out(IElementType input) {
        System.out.println("Matched [" + yytext() + "] as " + input);
        return input;
    }


  LiveScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LiveScriptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        System.out.println("End of file reached, clearing out indentation stack.");
    _currentIndent = 0;
    _indents.clear();
    return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL-1] : zzBufferL.charAt(zzMarkedPosL-1))) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { System.out.println("I> text is [" + yytext() + "], dedenting");
            _rewind();
            return _parseIndent(0);
          }
        case 24: break;
        case 14: 
          { _exitState(); return LiveScriptTypes.STRING_END;
          }
        case 25: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 26: break;
        case 10: 
          { if (_exitState()) _rewindBy(1);
          }
        case 27: break;
        case 22: 
          { _enterState(STRING_SUSPENDED); return LiveScriptTypes.STRING_END;
          }
        case 28: break;
        case 23: 
          { return LiveScriptTypes.HEREDOC;
          }
        case 29: break;
        case 13: 
          { return LiveScriptTypes.STRING;
          }
        case 30: break;
        case 12: 
          { _rewindTo("#"); _exitState(); return TokenType.WHITE_SPACE;
          }
        case 31: break;
        case 5: 
          { return _out(LiveScriptTypes.NEWLINE);
          }
        case 32: break;
        case 8: 
          { return LiveScriptTypes.COMMENT;
          }
        case 33: break;
        case 2: 
          { return LiveScriptTypes.NUMBER;
          }
        case 34: break;
        case 15: 
          { _exitState(); return LiveScriptTypes.IDENTIFIER;
          }
        case 35: break;
        case 9: 
          { return _out(TokenType.WHITE_SPACE);
          }
        case 36: break;
        case 17: 
          { _exitState(); return LiveScriptTypes.STRING_START;
          }
        case 37: break;
        case 4: 
          { _enterState(SIMPLE_STRING_STARTED); return LiveScriptTypes.STRING_START;
          }
        case 38: break;
        case 16: 
          { _rewindBy(1); _enterState(YYINITIAL);
          }
        case 39: break;
        case 6: 
          { _enterState(FULL_STRING_STARTED); return LiveScriptTypes.STRING_START;
          }
        case 40: break;
        case 21: 
          { _rewind(); _rewindBy(-1); _enterState(STRING_VARIABLE); return LiveScriptTypes.STRING;
          }
        case 41: break;
        case 20: 
          { System.out.println("State is " + yystate() + ", text is [" + yytext() + "]");
        _rewindBy(1);
        IElementType result = _parseIndent(yylength());
        if (result != null) return result;
          }
        case 42: break;
        case 7: 
          { return LiveScriptTypes.OPERATOR;
          }
        case 43: break;
        case 19: 
          { return LiveScriptTypes.BACKSTRING;
          }
        case 44: break;
        case 18: 
          { return LiveScriptTypes.RESERVED_LITERAL;
          }
        case 45: break;
        case 3: 
          { return _out(LiveScriptTypes.IDENTIFIER);
          }
        case 46: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
